grafana:
  enabled: true
  defaultDashboardsEnabled: true
  service:
    type: ClusterIP
  sidecar:
    datasources:
      enabled: true
      label: grafana_datasource

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    podMonitorNamespaceSelector: {}

alertmanager:
  enabled: false
