apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-orders-api
  namespace: observability
  labels:
    app: go-orders-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-orders-api
  template:
    metadata:
      labels:
        app: go-orders-api
    spec:
      containers:
        - name: server
          image: docker.io/amir23156/go-orders-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: PORT
              value: "5000"
            - name: ENVIRONMENT
              value: eks
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: otel-collector.observability.svc:4317
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: go-orders-api
  namespace: observability
  labels:
    app: go-orders-api
spec:
  selector:
    app: go-orders-api
  ports:
    - name: http
      port: 5000
      targetPort: http
  type: ClusterIP
